server:
  port: 4000

logging:
  level:
    org.springframework.web: ERROR
    com.tmtu: ERROR
  #pattern:
    #console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    #file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: D:/Kfas Naveen Data/SpringBoot_BusMamangementSystem/Spring-logging/application.log

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdb_test
    username: postgres
    password: 1234
  jpa:
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true 
    database-platform: org.hibernate.dialect.PostgreSQLDialect